services:
  fyyer-db:
    image: postgres:14.9
    volumes:
      - fyyer_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - fyyer-network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL:
        admin@example.com
      PGADMIN_DEFAULT_PASSWORD: insecurepassword
    ports:
      - "5050:80"
    networks:
      - fyyer-network

networks:
  fyyer-network:
    driver: bridge

volumes:
  fyyer_postgres_data: